### ISSUE TITLE
Mod loading support

### ISSUE THREAD

**Issue by karl-ulyanov** [FezVrasta/ark-server-tools#126]
Are you guys planning on adding support for using workshop mods?
I think it would be a nice idea and just requires modifying the server launcher parameters.

**Comment by klightspeed** [comment]
The latest stable version of arkmanager should already support modded maps.  Change `serverMap` in arkmanager.cfg to the name of the map, and add an `ark_ModId` setting in arkmanager.cfg

1.3-dev supports safe updating and backups with modded maps.

If multiple ModId parameters are required, then perhaps we can modify the argument handling to support arrays.

**Comment by karl-ulyanov** [comment]
Wow that is really awesome. Works great!

**Comment by MurdockNL** [comment]
hello i want to load multiple mod how do i do it ark-server-tools

**Comment by klightspeed** [comment]
Until the ARK developers add the ability to just specify the Mod IDs (see the **a little further out** section of the [ARK: Survival Evolved Change Notes](http://steamcommunity.com/app/346110/discussions/0/594820656447032287/)), you will need to copy the mods to `$arkserverroot/ShooterGame/Content/Mods`.

For map mods, if you have the latest 1.3-dev version, you can set the `ServerMapModId` option in arkmanager.cfg to the map mod ID; otherwise, set `ServerMap` option in arkmanager.cfg to the path of the mod map (as instructed in your map mod).

For additional mods, add an `ark_GameModIds` option in arkmanager.cfg with the comma-delimited list of mods - search for `GameModIds` on the [ARK: Survival Evolved Change Notes](http://steamcommunity.com/app/346110/discussions/0/594820656447032287/)
