### ISSUE TITLE
Signal 11 caught.

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#133]
Hi since the last update of ARK i've got that :+1: 
13:42:49: start
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager: line 204:  1741 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts"
13:47:41: exited with status 0

is there a solution ? 

thanks

**Comment by klightspeed** [comment]
See http://steamcommunity.com/app/346110/discussions/0/535151589911281824/#c535151589911306856

**Comment by Klik131** [comment]
Hello. Who found a solution to the problem?

**Comment by Atriusftw** [comment]
This is not related to our tools - there is a problem in the linux binaries that the ARK engineers have to solve. Just sit back and wait for a hotfix from them.

**Comment by Lihis** [comment]
ARK devs pushed out the fix: http://steamcommunity.com/app/346110/discussions/0/535151589911281824/#c535152276583856536

Updated from 189.0 to 190 after they pushed out the fix. Half an hour after the update the server is still up and running without problems.

**Comment by Atriusftw** [comment]
A small summary;

It was the initial 190 patch that broke the linux binaries, 3-4 hours later they managed to push out an unversioned hotfix, but SteamCMD was getting DoSed as a result of server admins trying to snatch the hotfix.

This issue is now fixed, but the performance on linux servers are horrible now.
Uses way too much CPU.
