### ISSUE TITLE
arkmanager upgrade ask for root password on a unprivileged user

### ISSUE THREAD

**Issue by OnigamiSama** [FezVrasta/ark-server-tools#170]
Everytime I launch a arkmanager upgrade command it ask for a root password  but I don't really want to put my gameserver user on the sudoer file.

It would be great to upggrade arkmanager without root privileges.

If there is no way to do so, we can always run sudo -u "user" arkmanager upgrade but it's not very "user friendly" if you knw what I mean.

**Comment by klightspeed** [comment]
Root privileges are required to write into /usr and /etc.

If you want to perform a user-install, then install as the user using the special `--me` argument, and add `$HOME/bin` to the front of the user's `PATH`.  This will of course not install the init scripts, since the install script needs to run as root to do that.

**Comment by klightspeed** [comment]
If you did perform a user-install, you will need to change `steamcmd_user` in `~/.arkmanager.cfg` from `me` to `--me`.

I will submit a hotfix for this.

**Comment by Atriusftw** [comment]
https://github.com/FezVrasta/ark-server-tools/pull/171 merged into master.
