### ISSUE TITLE
STEAMPS3 - AsyncTCPSocket created

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#221]
Hi on my arkserver.log

i've got that : 

STEAMPS3 - TCPPort::OnAcceptEvent (tcpport=0x7f43e119ef30), (socket=0x7f43e0c27308), (incoming.addr=77.56.130.119:62337)(incoming_=0)
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - TCPPort::OnAcceptEvent (tcpport=0x7f43e0617f70), (socket=0x7f43e1040b98), (incoming.addr=77.56.130.119:63345)(incoming_=0)
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed

is it possible to fix that ?

**Comment by klightspeed** [comment]
https://steamcommunity.com/app/346110/discussions/0/530646715633857478/

Those messages are often associated with lag, and seems to occur with any game that uses Steam P2P.  There is a report (with another game) that increasing the timeout resolved it.

**Comment by Atriusftw** [comment]
Correct. SteamP2P uses TCP sockets.
These log messages occurs when the connection between the server and player is unstable and causes packet loss. Since TCP is a reliable protocol, it resends the packet if it was lost. That's what you're seeing in the log.

Usually not a problem server-side. Most likely caused by a players with bad interwebs.

**Comment by arkfrancegaming** [comment]
rawsocket (udp) should fix that... but which is fixing rawsocket then ? lol

**Comment by Atriusftw** [comment]
The log messages you're referring to isn't a problem.
It's just notifying you that there are sync issues between your server and a client.

UDP is a faster protocol as it isn't reliable (i.e it doesn't resend packets that haven't been recieved)
Though the devs have stated that there are some stability issues with UDP at the moment.

**Comment by RainOfPain125** [comment]
Bumping this as this is still a persistent problem amongst other games as well and not just ARK. I run my own servers and waves of people get disconnected following a quick created and destroyed socket.

People have said things along the lines of "Usually not a problem server-side. Most likely caused by a players with bad interwebs." however, it would make zero sense for multiple people to get disconnected at once - so there must be something server-side.

**Comment by klightspeed** [comment]
If you're having this issue with multiple game servers on the same virtual or physical server, is this associated with either a connectivity issue or any logged messages in the kernel log?

**Comment by RainOfPain125** [comment]
@klightspeed Physical machine owned by me. Not sure what you mean by either of those, but the logs go as follows.

Disconnecting: PlayerID: 76561198192695189 Name: treep.garcia Character: [URSS-Sld-E1] Daniel
Disconnecting: PlayerID: 76561198059553575 Name: te Character: Master Maguku
Disconnecting: PlayerID: 76561198251320814 Name: Olakace78 Character: Si se te cay el jabon llego yo:v
Disconnecting: PlayerID: 76561198114108266 Name: mrkremk Character: kaboom
Disconnecting: PlayerID: 76561198176529789 Name: elZizar Character: elZizar
Disconnecting: PlayerID: 76561198156501959 Name: ImNotHydro Character: HydroGaming
Disconnecting: PlayerID: 76561198131422245 Name: Key Character: Sergeant Key
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created

I posted about it here - https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/380 - Where it should belong, however I've been going into other communities lately that are experiencing the same problems trying to juice out a solution.

**Comment by klightspeed** [comment]
Connectivity issue:  If you perform a continuous ping, are there any dropped packets around the time that the disconnects occur?

Kernel logs:  Is anything mentioned in either `/var/log/messages` or the output of `dmesg` around the time the disconnects occur?

**Comment by RainOfPain125** [comment]
Continuous ping? I'm not constantly pinging my server, and if I were I'd have to go through a whole lot of logs to find when it happens. What would even be the point of it? This happens for a split second and then bam, servers back to normal.

Kernal logs in /var/log/messages or output of dmesg? Sure you aren't talking about the game Im talking about? I already stated I host from other games and the same problems are plaguing the game I host for.

**Comment by klightspeed** [comment]
For connectivity issues, one can set up a SmokePing server, which can notify you the moment there is an issue, and which will show graphically any connectivity issues.

The reason I suggested looking in the kernel logs is to see if there is a CPU stall or something similar that occurs around the time of the dropped connections.

Another thought - since this is a physical machine you own, do you have a static IP address or a dynamic IP address with your ISP?  It's possible that this occurs when your internet connection goes down for a short period.

**Comment by RainOfPain125** [comment]
If my Ip is 'dynamic' then it hasn't changed in the past 3 months. My local IP is constant and I set it up to be that way / not use DHCP. Also, if it was something to do with my IP being dynamic my internet would go down and *everyone* would disconnect. However, that is not the case. Only a handful of people are disconnected

And I have no idea what you mean by kernal / kernal logs. Assuming that your talking about linux, linux kernals, and linux distro's I am running a copy of windows, not linux.
