### ISSUE TITLE
Broadcast Error

### ISSUE THREAD

**Issue by PromptlyDev** [FezVrasta/ark-server-tools#234]
I am getting the following error, when trying to broadcast a message:

Error connecting to server at -e line 31.

My Command:
arkmanager useconfig pve broadcast "My message"

**Comment by PromptlyDev** [comment]
Also the status command is broken:
 Server running:   Yes
 Server online:   Yes
Unable to query server
 Server version:   809694

**Comment by klightspeed** [comment]
This is likely due to your multi-homing.  Both the server status querying and the rcon command sender try to connect to localhost (127.0.0.1), while when you have MultiHome set the server does not bind to that address.  lsof on the other hand looks for the port on any address when the address is not specified, thus saying that the server is online.
