### ISSUE TITLE
Mod-updates feature request

### ISSUE THREAD

**Issue by morggin** [FezVrasta/ark-server-tools#242]
Are the update switches stackable? can i do arkmanager update --warn --update-mods ?
also would it be possible to add the check feature to --update-mods? so it will check for mods updates and only apply if there are changes?

**Comment by klightspeed** [comment]
The update switches are indeed stackable.

The mod update feature will download the mods (since steamcmd provides no way of checking if a mod has been updated), and then compares the modification times on the downloaded mod files with those already installed.  If none of the files have changed, then it will cancel the mod update unless the `--force` switch is specified.

**Comment by Budman17r** [comment]
About this, if the file is modified but not any new, the update mods doesn't seem to update.

**Comment by klightspeed** [comment]
@Budman17r please create a new issue for this.

**Comment by klightspeed** [comment]
This is now in the stable branch.
