### ISSUE TITLE
Add command line option to enable/disable a specific mod

### ISSUE THREAD

**Issue by ajziehl** [FezVrasta/ark-server-tools#361]
Thoughts on adding a command line option to enable/disable a specific mod? Usage something like:

    arkmanager enablemod 479295136
    arkmanager disablemod 479295136

In the above example, enabling would enable the Aku Shima mod by appending the mod id to ark_GameModIds in the config file. Disabling would do the opposite, take that mod out of the ark_GameModIds list.

An issue I forsee is if the ark_GameModIds are specified in an alternate config file.

**Comment by klightspeed** [comment]
One issue with this is that some mods must be loaded in a specific order.

**Comment by FezVrasta** [comment]
What if you just have a list of mods with the flag enabled/disabled?

In this way you keep the order of them and you can still enable/disable them by cli

**Comment by FezVrasta** [comment]
Example:

12346 = true
64644 = false
87677 = true

**Comment by klightspeed** [comment]
So in the instance config file (until we can change the config format to a more ini-style format):

```
arkmod_12346=true
arkmod_64644=false
arkmod_87677=true
```

**Comment by ajziehl** [comment]
So potentially something like

    set -o posix ; set | grep "^arkmod_" | grep "=true"

to get that list of enabled

**Comment by klightspeed** [comment]
Perhaps if we store the config filename in a variable, and then:

```
ark_GameModIds="$(sed -n 's|^arkmod_\([0-9]*\)=true.*|\1|' "${arkstConfigFile}" | tr '\n' ',' | sed 's|,$||')"
```

**Comment by Nodens-** [comment]
Would it not be better adding a .cfg file that lists mods with priority, dependencies and friendly_name attributes so the script can handle dependencies and ordering automatically when you enable/disable mods and can use a friendly name for it instead of having to remember or copy/paste the id number?
`mod1id=14412412`
`mod1prio=1`
`mod1dep=2,4,5`
`mod1fn=mymod`

So loading it, you know you have to load mod2id, mod4id and mod5id prior to mod1id in that order and mod1id has priority in the order over everything else (as it's set to 1) apart from its dependencies. That way you can create as complex mod configurations as you may require simply by appending them to the .cfg and have a very easy way to enable/disable at will via arkmanager without needing extra switches or on-the-fly ordering.

**Comment by klightspeed** [comment]
@Nodens- Are you suggesting having a registry of mods?  Are you also offering to maintain that registry?  There are currently 778 mods on the Steam workshop.

**Comment by Nodens-** [comment]
@klightspeed No, that would be a feat in itself and very time consuming. .cfg file would be user created with their mods of choice etc. They would have to maintain it themselves, arkmanager just has to parse it and provide an empty file with commented syntax example.

**Comment by klightspeed** [comment]
I have now implemented basic `arkmod_*` option support, with `enablemod` and `disablemod` commands.  It is up to the server administrator to order them in the config as they should be loaded.

**Comment by klightspeed** [comment]
Added in v1.6
