### ISSUE TITLE
Bad output of arkdaemon status on systemd 

### ISSUE THREAD

**Issue by Sispheor** [FezVrasta/ark-server-tools#47]
What we should have
```
Server running:  No
Server online:   No
Server version:  665994
````

What we really have
```
root@nas:/home/steam/ark-server-tools/tools# /etc/init.d/arkdaemon status
● arkdaemon.service - LSB: ARK manager deamon
   Loaded: loaded (/etc/init.d/arkdaemon)
   Active: inactive (dead) since mer. 2015-06-24 19:31:37 CEST; 1min 5s ago
  Process: 765 ExecStop=/etc/init.d/arkdaemon stop (code=exited, status=0/SUCCESS)
```

Tested on the last revision of 1.1 banch on Debian 8. I think it's the same on CentOS7 and other distro who used systemd.

**Comment by klightspeed** [comment]
This suggests that /lib/lsb/init-functions on Debian 8 is hijacking the status request and redirecting it to systemctl.

When I tested it on CentOS 7 last night (with #46 applied), `service arkmanager status` gave the expected output.

Since the 'status' action is a standard action that has special handling on different systems, should the 'status' action in the init script be renamed to something like 'arkstatus'?

**Comment by FezVrasta** [comment]
it's weird, if you run `service iptables status` you get a custom output from it, so why can't we do the same?

Maybe you may look at the iptables daemon and see how they do it.

**Comment by FezVrasta** [comment]
Reading here: http://comments.gmane.org/gmane.comp.sysutils.systemd.devel/3050

systemd doesn't support the `status` command for its services

**Comment by klightspeed** [comment]
From what I can find, systemd doesn't support custom actions.  There was a discussion on the Fedora mailing list about adding "legacy" actions to `system` when running under systemd: https://lists.fedoraproject.org/pipermail/devel/2012-June/169431.html

That conversation you quoted also says that a pidfile needs to be created in order to determine if the daemon is still alive.  pidfiles are usually created as /var/run/<daemon>.pid

**Comment by FezVrasta** [comment]
so how we proceed?

**Comment by Sispheor** [comment]
If it's not a supported action by systemd we just document it. 
We should split sysvinit and system daemonark script. And add the requiered PID to the systemd one.

**Comment by klightspeed** [comment]
It looks like, at least for iptables, RHEL 7 based distributions (including Fedora and CentOS) put the original sysvinit script into /usr/libexec/<service>/<service>.init, and calls that from the systemd start, stop and reload actions.

**Comment by FezVrasta** [comment]
Do we want to wait this fix before we release 1.1 or can we ship without the `status`support?

**Comment by Sispheor** [comment]
Let me tonight to try to fix this.

2015-06-25 12:16 GMT+02:00 Fez Vrasta <notifications@github.com>:

> Do we want to wait this fix before we release 1.1 or can we ship without
> the statussupport?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/47#issuecomment-115199681>
> .
>



-- 
*Nicolas MARCQ*

**Comment by FezVrasta** [comment]
any news?

**Comment by Sispheor** [comment]
No time to code :(

**Comment by FezVrasta** [comment]
Can we ship however? We can push an hotfix in case.

**Comment by Sispheor** [comment]
Yep. Go merge, tag and rebase the 1.2.

**Comment by FezVrasta** [comment]
Any news?

**Comment by Sispheor** [comment]
It's not really a bug. It's a normal systemd 's output. If we want to sown the same output we must switch from "status" to another word.

**Comment by Sispheor** [comment]
I think you can close this issue. It's a normal output for systemd. If the user want the correct output he has to use "arkmanager status".

**Comment by Atriusftw** [comment]
Alright, closing issue.
