### ISSUE TITLE
arkmanager.cfg not working?

### ISSUE THREAD

**Issue by EddyThePro** [FezVrasta/ark-server-tools#549]
So basically the instructions say that the file would be at /etc/arkmanager/ but its not... Its at ~/.arkmanager.cfg instead. So I edited some things in the file like the max number of slots and I changed the admin password, but every time I start the server it just re-writes the GameUserSettings.ini file back to the default arkmanager.cfg settings. Keyboardcat and the default 70 slots. This happens every time I try to run the server.

The arkmanger.cfg file on the other hand stays with the changes, but still re-writes the GameUserSettings.ini even tho it shouldn't be.

**Comment by klightspeed** [comment]
It sounds like you did both a system-wide install and a user-install.

> To install ARK Server Tools run this command:
> ```
curl -sL http://git.io/vtf5N | sudo bash -s steam
```

...

> To __instead__ perform a user-install of ARK Server Tools as an unprivileged user, run this command:
> ```
curl -sL http://git.io/vtf5N | bash -s -- --me
```

`~/.arkmanager.cfg` (the user's config file) overrides settings in `/etc/arkmanager/arkmanager.cfg` - see https://github.com/FezVrasta/ark-server-tools#configuration-files

If you don't want to use `~/.arkmanager.cfg`, then remove that file.

Since you did a user-install, the instance config file will be in `~/.config/arkmanager/instances/main.cfg` - see https://github.com/FezVrasta/ark-server-tools#instance-config-files

If you don't want to use `~/.config/arkmanager/instances/main.cfg`, then remove that file.

**Comment by EddyThePro** [comment]
Thanks for the help!
