### ISSUE TITLE
Server config

### ISSUE THREAD

**Issue by Betaman2k** [FezVrasta/ark-server-tools#6]
Heya

great work, now dl time.
Pre question, any server config files for player limits etc ?

[ServerSettings]
DifficultyOffset=0.200000
GlobalVoiceChat=False
ServerPVE
ServerHardcore 
ServerCrosshair 
ServerForceNoHUD 
AltSaveDirectoryName 
GlobalVoiceChat 
NoTributeDownloads
AlwaysNotifyPlayerLeft
DontAlwaysNotifyPlayerJoined
AllowThirdPersonPlayer
MapPlayerLocation

Perhaps had u a good config file for PvE server, thx
regards
Betaman

**Comment by FezVrasta** [comment]
no I've not any config file right now, we'll add them later I guess. Feel free to share if you find some good one.

**Comment by Betaman2k** [comment]
Heya
hmmm, no confic for ark server, i mean playerli mit etc  how many player can played on a new server ( 70 player ) ?

**Comment by Atriusftw** [comment]
You can append the following to your GameUserSettings.ini:

`[/script/engine.gamesession]`
`MaxPlayers=70`

**Comment by Levistras** [comment]
Can we add an option in the .arkmanager.cfg to append command line arguments for launch?

I've gone in and manually changed /usr/bin/arkmanager, but this is probably not the best solution.

>> arkserveropts="TheIsland?QueryPort=$arkserverport?ServerPassword=$arkserverpass?ServerAdminPassword=$arkserverapass?listen?MaxPlayers=30?AllowThirdPersonPlayer=True?ServerCrosshair=True?ServerPVE=True?MapPlayerLocation=True?DifficultyOffset=0?SessionName=[ The Saurian Isles ]"

It would be nice if I could put the part that I'm appending, "?MaxPlayers=30?AllowThirdPersonPlayer=True?ServerCrosshair=True?ServerPVE=True?MapPlayerLocation=True?DifficultyOffset=0?SessionName=[ The Saurian Isles ]", in the .arkmanager.cfg so that it will carry over once the main arkmanager is updated.

Cheers!

**Comment by FezVrasta** [comment]
you can now configure any option directly inside arkmanager config, it's in dev 1.1 currently, will land to stable soon
