### ISSUE TITLE
Segmentation fault since update 254

### ISSUE THREAD

**Issue by N-Rico** [FezVrasta/ark-server-tools#727]
Hi,

I've been running ark-server-tools without any real problems for about a month now, but today my server fails to start. This morning I updated Ark to v254 (1600359), it ran for a while but this evening it crashed and I can't get it running again.

When I try to start it non daemonized I get:
_Running command 'run' for instance 'main'
2017-01-31 23:08:13: start
2017-01-31 23:08:13: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer ScorchedEarth_P\?MaxPlayers=30\?GameModIds=510590313\,523835795\,566887000\,731604991\?listen -UseBattlEye
2017-01-31 23:08:13: Server PID: 15640
Using binned.
4.5.1-0+UE4 7038 3077 402 7
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
EngineCrashHandler: Signal=11
/usr/local/bin/arkmanager: line 941: 15640 Segmentation fault      (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2017-01-31 23:08:18: Bad PID ''; expected '15640'
2017-01-31 23:08:18: exited with status 0_

Please advise!

Enrico

**Comment by N-Rico** [comment]
Hm, reinstalled server files with 'arkmanager install' and now it seems to work...for now at least.

**Comment by N-Rico** [comment]
I would like to reopen this issue, ever since the 254 update of Ark I find my server not running when I check in the morning (I have a cronjob scheduled for 4:15am doing "arkmanager update --warn --saveworld --update-mods"). At first I thought it to be a problem with Ark itself, because starting the server manually would result in the same 'Signal 11' crash, but I've come to suspect the 'arkmanager update' command being the culprit.

Things I've tried so far:

- tried starting it without using arkmanager, but same result.
- tried running without mods, same result.
- tried running without BattleEye, same result. 
- tried starting the server with a fresh ark, same result.
- tried running arkmanager update --validate, same result.
- tried running 'arkmanager install' again, server fixed, until next armanager update!
- tried running 'steamcmd +login anonymous +force_install_dir <install_dir> +app_update 376030 validate +quit, server works again.

For now I've disabled the update cron, yesterday I tried manually updating through arkmanager, and the server was broken again (same error: line 941 <pid> segmentation fault). Fixed it with steamcmd app_update 376030 validate. This morning I forced an update using steamcmd.sh, and server kept working.

**Comment by klightspeed** [comment]
If you are using a staging directory, try deleting and re-creating it.

**Comment by rob-bb** [comment]
I have been having a similar but not exactly the same issue for a while (2 months?)

The server is just not running, ark manager is in a loop of starting it, ti crashes and ark manager starts ti again.  This is probably after an update as I do a check every 30 mins.

If I remove all mods, still crashes.  If I remove about half the mods (at random I insert a ," # into the line) the server starts, I can then remove my line separator and restart with all the mods and it works.  Ofcourse the saved would is now broken form the mods that were missing so I need t od oa restore as well.

But this is random, it will happen twice in a week then not for 3 weeks and so on.  I don't know where the problem is, havn't been to concerned as it is a test server and not in use by players.

**Comment by N-Rico** [comment]
Hi klightspeed,

that seemed to do the trick, I'll reenable the cronjob and keep a close eye on it.

Is there any way to prevent this?

Thanks!

**Comment by N-Rico** [comment]
All seems good now, thanks again!
