### ISSUE TITLE
CronJob

### ISSUE THREAD

**Issue by Redeye123** [FezVrasta/ark-server-tools#889]
Hello im very new to linux so i hope you don't mind me asking this .

Ive got 4 servers running and wanted a more Automated way of updating so i thought the cronjob command would be the perfect way for that but not sure how i need to set this up .

like this ? or can there be only one arg ?
arkmanager install-cronjob update --arg=update-mods --arg=warn --hourly

**Comment by klightspeed** [comment]
```
arkmanager install-cronjob --hourly update --update-mods --warn
```

**Comment by Redeye123** [comment]
Awesome very appriciated

**Comment by SinisterSole** [comment]
I know this is closed but is there a need to put the instance at the end ie. (@all for all)?
./arkmanager install-cronjob --hourly update --update-mods --warn @all

**Comment by klightspeed** [comment]
The instance name can go anywhere between the `install-cronjob` command and
the end of the argument list.

If the instance is not specified, then it will act on the default instance,
or ask if you wish to run it on all instances if no default instance is
configured.

On 28 Dec 2017 12:58 PM, "SinisterSole" <notifications@github.com> wrote:

I know this is closed but is there a need to put the instance at the end
ie. (@ALL <https://github.com/all> for all)?
./arkmanager install-cronjob --hourly update --update-mods --warn @ALL
<https://github.com/all>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/FezVrasta/ark-server-tools/issues/889#issuecomment-354213413>,
or mute the thread
